spring.application.name=conexion-bd

# Conexión a la base de datos 
spring.datasource.url=jdbc:postgresql://dpg-d8ccop28qa3s73bggo00-a.frankfurt-postgres.render.com:5432/prog_4
spring.datasource.username=luca_escudero
spring.datasource.password=${DB_PASSWORD}

# Usar variable de entorno para la contraseña. Nunca hardcodear.

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA/Hibernate 
spring.jpa.hibernate.ddl-auto=update

 # Valores: none | validate | update | create | create-drop
spring.jpa.show-sql=true 

# Imprime el SQL en consola (solo desarrollo)
spring.jpa.properties.hibernate.format_sql=true

# Pool de conexiones (HikariCP, incluido en Spring Boot) 
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
